import './global.css';
import Providers from './providers'; // Importamos el provider que acabamos de crear

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Envolvemos todo el contenido con nuestro Provider */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}